name: Publish Django distributions to PyPI and TestPyPI

on: push

jobs:
    build-n-publish:
        name: Buildd and publish Django distributions to PyPI and TestPyPI
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@main
            - name: Set up Python 3.8
            uses: actions/setup-python@v1
            with:
                python-version: 3.8
            - name: Install pypa/build
                run: >-
                    python -m
                    pip install
                    build
                    --user
            - name: Build a binary wheel and a source tarball
                run: >-
                    python -m
                    build
                    --sdist
                    --wheel
                    --outdir dist/
                    .
            - name: Publish distribution to Test PyPI
                uses: pypa/gh-action-pypi-publish@main
                with:
                    password: ${{ secrets.TEST_PYPI_API_TOKEN }}
                    repository_url: https://test.pypi.org/legacy/
            - name: Publish distribution to PyPI
                if: startsWith(github.ref, 'refs/tags')
                uses: pypa/gh-action-pypi-publish@main
                with:
                    password: ${{ secrets.PYPI_API_TOKEN }}